#+title: =auto-capitalize.el=
#+author: Abdulnafé Toulaïmat
#+language: en_US

Automatically capitalize text as you type.

* Installation

Put =auto-capitalize.el= somewhere in your load-path, then put this in your =.emacs=:

#+begin_src elisp
  (require 'auto-capitalize)
  (auto-capitalize-global-mode)
#+end_src

This enables capitalization in all =text-mode= buffers, as well as in comments and strings in =prog-mode= and any other mode that defines them.

If you use =use-package=, you can use this snippet instead:

#+begin_src elisp
  (use-package auto-capitalize
    :init
    (auto-capitalize-global-mode))
#+end_src

If you’re interested in using this package in your Org or TeX documents, then consider using the provided plugins =auto-capitalize-org.el= and/or =auto-capitalize-tex.el=, like so:

#+begin_src elisp
  (use-package auto-capitalize
    :init
    (auto-capitalize-global-mode)
    :hook
    ((TeX-mode-hook . auto-capitalize-tex-mode)
     (org-mode-hook . auto-capitalize-org-mode)))
#+end_src

This will give you markup-aware capitalization in those modes, such as capitalizing text inside of any TeX macro listed in the user option =auto-capitalize-tex-macro-whitelist=, as well as preventing capitalization in environments such as math, equation etc.

And that’s pretty much it. Start typing to try it out!

* Requirements

The core package requires =font-lock= to detect comments and strings, since it relies heavily on =syntax-ppss=. =auto-capitalize-tex.el= requires [[https://www.gnu.org/software/auctex/][AUCTeX]].

* Customization

Things should just work for most users, with sensible defaults. However, there are customization options in the =auto-capitalize= group. Those should let you get the behavior you want.

If you want to limit auto-capitalization to certain modes instead of enabling it globally, replace =auto-capitalize-global-mode= in the snippets above with =auto-capitalize-mode=, which is the buffer-local version. You can add that to any mode’s hook you want. For example, to only enable =auto-capitalize.el= in text-mode buffers, but not prog-mode, you could say:

#+begin_src elisp
  (use-package auto-capitalize
    :hook
    text-mode)
#+end_src

** User options

You can set the following boolean options for more fine-grained control:
   
   | Variable                                 | Default value | Description                                                                                          |
   |------------------------------------------+---------------+------------------------------------------------------------------------------------------------------|
   | =auto-capitalize-strings=                  | =t=             | Capitalize strings in modes where they are defined                                                            |
   | =auto-capitalize-comments=                 | =t=             | Capitalize comments in modes where they are defined (prog-mode, org-mode, etc)                       |
   | =auto-capitalize-ask=                      | =nil=           | Ask the user before automatically capitalizing anything                                              |
   | =auto-capitalize-yank=                     | =nil=           | Capitalize yanked text as well as typed text                                                         |
   | =auto-capitalize-outline-headings=         | =t=             | Capitalize the first word in headings in text-mode-derived buffers (Org, TeX,...)                    |
   | =auto-capitalize-start-of-inline-comments= | =t=             | Capitalize the first word in inline comments. This has no effect if =auto-capitalize-comments= is nil. |
   | =auto-capitalize-start-of-inline-strings=  | =nil=           | Capitalize the first word in inline strings. This has no effect if =auto-capitalize-strings= is nil    |

More explanations are in each variable’s respective doc string.

The mode is defined by =define-globalized-minor-mode=, which means you get access to =auto-capitalize-global-modes=, which is a list of modes in which to enable (or disable if preceded with a =not=) the global mode.

=auto-capitalize-fixed-case-words= is a list of words whose case will always be exactly how it appears in the list. For example, the English pronoun "I" - the only default entry - will replace any lowercase "i" followed by any character in =auto-capitalize-trigger-chars=. You can, of course, customize =auto-capitalize-trigger-chars= as well!

No capitalization takes place if the word of interest happens to be right after one of the entries in =auto-capitalize-abbrevs=. This is a list of abbreviations, such as "i.e." and "e.g.", which contain periods but don’t actually mark the end of a sentence. Thus, typing "i.e. you" will not capitalize the "y".

Note that the lists =auto-capitalize-abbrevs= and =auto-capitalize-fixed-case-words= must be set with either =setopt= or the =customize= interface, otherwise your changes will not take effect. In specific, it is not enough to just use =add-to-list= to add elements to either of these variables.

Finally, for true control, there is the core of the capitalization logic. The package exposes two hooks as user-options: =auto-capitalize-blocking-functions= and =auto-capitalize-trigger-functions=. You can add your own predicates to either of these two hooks.

** =auto-capitalize-blocking-functions= and =auto-capitalize-trigger-functions=

- =auto-capitalize-blocking-functions= get called first. These are predicates that take no input and return non-nil to indicate that they want to block capitalization in the current context. If any of these functions return non-nil, capitalization does not occur.

- =auto-capitalize-trigger-functions= get called later. These are predicates that take two arguments, =text-start= and =word-start=, and return non-nil to trigger capitalization.

Note the symmetry in semantics: a single blocking function returning non-nil will block capitalization, whereas, assuming all blocking functions pass, a single trigger function returning non-nil will trigger capitalization.

Note also that just because no blocking function blocks capitalization in a given context does not mean it will occur: /at least one/ trigger function must return non-nil for capitalization to actually happen.

By default, only =auto-capitalize-default-blocking-function= and =auto-capitalize-default-trigger-function= are included in the hooks. The companion Org and TeX plugins, =auto-capitalize-tex.el= and =auto-capitalize-org.el=, also register their own blocking and trigger functions when their respective modes are enabled.

* How it works

The package’s main entry point is the function =auto-capitalize-capitalize=. The minor-mode adds it to =after-change-functions=, so it gets called as you type, delete, yank, etc. Its job is to run the first layer of logic: it moves point back across quotes and parentheses, then calls all functions in =auto-capitalize-blocking-functions=, and if they all return nil, either calls =auto-capitalize-maybe-capitalize-preceding-word= if you are simply typing, or recursively analyzes the text if you are yanking (and =auto-capitalize-yank= is non-nil).

=auto-capitalize-maybe-capitalize-preceding-word= and =auto-capitalize-handle-fixed-case= are the functions actually responsible for capitalizing words. The former checks if the word at point matches =auto-capitalize--fixed-case-regexp=, which is built from =auto-capitalize-fixed-case-words=. If it does, it calls =auto-capitalize-handle-fixed-case=, which simply replaces the word with its corresponding entry in =auto-capitalize-fixed-case-words=.

Otherwise, =auto-capitalize-maybe-capitalize-preceding-word= moves point back one char (so it lands right where it was before the change occured), and calls =auto-capitalize-trigger-functions=. Those functions then check to see if capitalization is appropriate in the current context, i.e. that the word is at the beginning of a sentence or a paragraph in text-mode, or a comment (if =auto-capitalize-comments= is non-nil), etc.

If all tests pass, voilà! Your word gets capitalized automatically.

* Writing plugins

The package is designed to be extensible to cover a number of limitations that the core can never fully address by itself, most importantly the fact that markup languages have their own syntax which should never be capitalized. For instance, the package does not understand HTML syntax, and so will happily (and incorrectly) capitalize HTML tags.

If you’re interested in writing a plugin for some markup language, you need to do three things:

  1. Define a blocking function. This is a predicate that takes no arguments, and if it returns non-nil, it blocks capitalization. When blocking functions are called, point is moved back accross opening parens and quotes.
  2. Define a trigger function. This is a predicate that takes two arguments: =tet-start=, the position before all open parens and quotes before the word of interest, and =word-start=, the position of the first letter in the word. This function should return non-nil to trigger capitalization in the current context.
  3. Define a minor-mode that adds those functions to the appropriate hooks buffer-locally

The Org and TeX plugins can serve as examples of what that might look like.

* Known issues

- =auto-capitalize-outline-headings= doesn’t work in =markdown-mode= buffers. This is because of the value that mode sets =outline-regexp= to, which differs in its semantics from other text modes. We could add specific support for it in the future, but that would add some complexity to the code.

  It also only affects the first word in a heading for now. Subsequent sentences within a heading are handled by the usual sentence-based rules.

- Even with =auto-capitalize-tex-mode=, quoted text in =TeX-mode= buffers, such as

  #+begin_src TeX
    ``some text here``
  #+end_src

  does not get capitalized. Again, this only affects the first word ("some" in the example), as the other rules apply as usual (beginning of a sentence, comment, etc).

- The package struggles with markup languages in general, hence the need for plugins that teach =auto-capitalize= different markup syntaxes.

Of course, if you have ideas on how to solve any of these issues or otherwise improve the package, PRs are more than welcome :)

* Alternatives

The modern auto-capitalization landscape in Emacs seems to have coalesced around [[https://elpa.gnu.org/packages/captain.html][captain]], which you can get from ELPA. =auto-capitalize.el= is an alternative, based on the classic package with the same name from all the way back in 1998. The main user-facing difference between this package and captain is that this package tries hard to define defaults that work out of the box, so that, ideally, you never have to write your own predicates if you don’t want to. Captain, on the other hand, is far lighter and more efficient, and much more modern in its approach.

* Credits & a bit of history

Kevin Rodgers wrote the original =auto-capitalize.el=. It got shared around the Emacs world and ended up on the [[https://www.emacswiki.org/emacs/auto-capitalize.el][emacswiki]], and from there it found its way to MELPA. But MELPA removed it for security reasons, along with other packages whose upstream was the wiki, back in [[https://github.com/melpa/melpa/pull/5008#issue-258144843][2018]].

The [[https://github.com/yuutayamada/auto-capitalize-el][fork by Yuta Yamada]] on GitHub is the basis for this package. Although it appears unmaintained now, the work he put into refactoring it was the starting point for this package.

Note that this package is not fully compatible with either the original or Yuta Yamada’s fork: the interface is different, and it drops XEmacs support entirely.
